<div align="center">
<form method="post" action="?action=admin" >

<table>
    <tbody>
        <tr><td><b>Логин администратора</b></td><td><input type="text" name="admin_name" /></td></tr>
        <tr><td><b>Пароль</b></td><td><input type="password" name="admin_pass" /></td></tr>
        <tr><td align="right" colspan="2"><input type="submit" value="Ввойти" /></td></tr>
    </tbody>
</table>
</form>
</div>